### PR TITLE
Add four-way intersection scenario

### PR DESCRIPTION
**Pull request by madan96**
Adds the four way intersection scenario with visualization and example.

TODOs:
- [ ] Verify collision constraints
- [x] Add centerline functions for turns.

### CODE REVIEW

**Comment by simon-lc** [comment]
Hi Madan, I looked at the video you sent. it seems that the issue was that you initialized a car outside its lane, so its behavior was to rejoin its lane as fast as possible. To get a 4-way intersection with vehicles turning left or right, you can define a lane "turn left", "turn right", "go straight" for each way (east, west, north, south) of the intersection. So that would 12 lanes for this intersection. 

The current way to define the lane is not intuitive and quite painful to write down. I took the code from your PR and created a branch in AlgamesDriving.jl "add_4_way_intersection". I wrote a demo with 3 lanes "west straight", "west left", "west right" and tested it so you should be able to run it easily.

You could try to 'rebase' your PR from the branch "add_4_way_intersection" and add the 9 remaining lanes. Then I can merge it to master quickly. 
Tell me if you have question about the code in "add_4_way_intersection"

image

**Comment by madan96** [comment]
Thanks for adding the turning lanes for west! It was really helpful in understanding how the centerline functions work. I have added the remaining lanes and it seems to be working pretty well. Also updated the visualization code to make it look like the image below.
intersection

**Comment by madan96** [comment]
@simon-lc I noticed this strange behavior where the two cars interchange there positions resulting in a collision, when I increased the amplitude of collision cost. Shouldn't the agents be more cautious about collisions after increasing this value? Also, is there a boolean value that tells if the solution results in a constraint violation? I'd be happy to help, if it doesn't exist yet.

https://user-images.githubusercontent.com/13871064/111500703-46db6a80-876a-11eb-84a4-f6bcb97b3900.mp4

**Comment by simon-lc** [comment]
The 4 way intersection visualisation looks good! I'll look at the latest commits in the PR and merge today if everything is okay.
The issue that shows up in the latest video happens when the trajectories of the vehicles are 'entangled'. There might not be any constraint violation because the constraints are only evaluated at the discrete knotpoints on the trajectory. 
There are a few ways to avoid this:
- increase the number of waypoints, 
- increasing the radius at which the collision avoidance cost is active (instead of the cost amplitude), 
- add a bound constraint on the controls to avoid having these large changes in speed and positions. 
- add a bound constraints on the velocity
For to boolean value indicating the constraint violation at the end of the solve. This should be easy to do. The GameProblem.stats contains all the constraint violations: on the control constraints, the state constraints, the optimality constraints, and the dynamics constraints. You can check the last violations at the end of stats to see what's the constraint 
at the end of the solve.

**Pull request merged**
